<a href="https://colab.research.google.com/github/k1selukkk/laba_0_data/blob/main/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Сводная таблица pivot_table

Сводная таблица - это мощный инструмент для обобщения и представления данных.

В Pandas для подготовки сводных таблиц вызывают метод **pivot_table()**.

Аргументы метода:

• index — ключи для группировки по индексу (строке)

• columns — ключи для группировки столбцов

• values — значения, по которым мы хотим увидеть сводную таблицу (столбцы для агрегирования)

• aggfunc — функция, применяемая к значениям (т.е. что делать с повторяющимися значениями)

<img src="https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/pic/pivot_table_pandas.png" >

Построим сводную таблицу для задачи по SEO-оптимизации.
Для начала загрузите дата-сет data.final, полученный в результате выполнения предыдущей задачи (объединения таблиц), сохраните ешл в переменной df.

In [ ]:
import pandas as pd
df = pd.read_csv('data_final.csv')

# Вывод первых строк для проверки
df_head = df.head()

df_head

,subcategory_id,source,visits,subcategory_name,category_id,category_name
0,cf2e61c7af,direct,501165,Мобильные телефоны,09f279a643,Электроника
1,0cd903d1cc,direct,126342,Ноутбуки,3509869a61,Компьютерная техника
2,ef35bc88a7,direct,95626,Телевизоры,09f279a643,Электроника
3,6ff9f4014c,direct,75680,Планшеты,3509869a61,Компьютерная техника
4,72bc238e4d,direct,64435,Наушники и Bluetooth-гарнитуры,09f279a643,Электроника

## Поворот данных

Создавать сводную таблицу **(pivot_table)** лучше всего последовательно. Добавляйте элементы по одному и проверяйте каждый шаг, чтобы убедиться, что вы получаете ожидаемые результаты. Самая простая сводная таблица должна иметь **DataFrame** и индекс **(index)**.

В этом примере давайте использовать **category_name** в качестве индекса:

**pd.pivot_table(df, index=["category_name"])**

In [ ]:
# Ограничение данных только числовыми столбцами перед созданием сводной таблицы
numeric_df = df.select_dtypes(include='number')

# Добавляем обратно категориальный столбец для группировки
numeric_df['category_name'] = df['category_name']

# Создание сводной таблицы с числовыми столбцами
pivot_simple_fixed = pd.pivot_table(numeric_df, index=["category_name"])

# Вывод результата
pivot_simple_fixed

                                  visits
category_name
Авто                         4328.489583
Бытовая техника              7012.164557
Дача, сад и огород           1511.142857
Детские товары               1657.736434
Досуг и развлечения           959.428571
Компьютерная техника        12523.693548
Оборудование                  475.884615
Одежда, обувь и аксессуары   1486.037500
Продукты                      595.454545
Спорт и отдых                2187.768519
Строительство и ремонт       1797.015152
Товары для дома              1047.264151
Товары для животных          1124.423077
Товары для здоровья          2332.558824
Товары для красоты           1451.812500
Электроника                 19661.201389

У вас может быть несколько индексов. Фактически, большинство аргументов **pivot_table** могут принимать несколько значений в качестве элементов списка. Добавьте в список индексов переменную **subcategory_name**.

In [ ]:
# Добавляем обратно столбец 'subcategory_name' для создания сводной таблицы
numeric_df['subcategory_name'] = df['subcategory_name']

# Создание сводной таблицы с несколькими индексами: category_name и subcategory_name
pivot_with_subcategory = pd.pivot_table(numeric_df, index=["category_name", "subcategory_name"])

# Вывод результата
pivot_with_subcategory

                                          visits
category_name subcategory_name
Авто          Автоакустика               10674.0
              Автомагнитолы              13236.5
              Автомобильные инверторы      147.5
              Автомобильные компрессоры    598.5
              Автомобильные телевизоры    1610.5
...                                          ...
Электроника   Чехлы                       8170.0
              Чехлы-аккумуляторы           275.0
              Штативы и моноподы          1846.0
              Экшн-камеры                 8566.5
              Электронные книги           7939.5

[934 rows x 1 columns]

Вы могли заметить, что сводная таблица достаточно умна, чтобы начать агрегирование данных и их обобщение, группируя категории товаров (**category_name**) с их подкатегориями (**subcategory_name**). Теперь мы начинаем понимать, что может сделать для нас сводная таблица.

Поскольку в данном случае столбец с количественной переменной только один (**visits**), он автоматически определился в качестве значения параметра **values**. Однако, можно явно определить столбцы, которые нам нужны, с помощью этого параметра **values**:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"])**

In [ ]:
# Создание сводной таблицы с явным указанием столбца 'values'
pivot_with_values = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"])

# Вывод результата
pivot_with_values

                                          visits
category_name subcategory_name
Авто          Автоакустика               10674.0
              Автомагнитолы              13236.5
              Автомобильные инверторы      147.5
              Автомобильные компрессоры    598.5
              Автомобильные телевизоры    1610.5
...                                          ...
Электроника   Чехлы                       8170.0
              Чехлы-аккумуляторы           275.0
              Штативы и моноподы          1846.0
              Экшн-камеры                 8566.5
              Электронные книги           7939.5

[934 rows x 1 columns]

Столбец цен (**visits**) по умолчанию усредняет данные, но мы можем произвести подсчет количества или суммы. Добавить их можно с помощью параметра **aggfunc**:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], aggfunc='sum')**

In [ ]:
# Создание сводной таблицы с использованием функции суммирования (aggfunc='sum')
pivot_with_sum = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], aggfunc='sum')

# Вывод результата
pivot_with_sum

                                         visits
category_name subcategory_name
Авто          Автоакустика                21348
              Автомагнитолы               26473
              Автомобильные инверторы       295
              Автомобильные компрессоры    1197
              Автомобильные телевизоры     3221
...                                         ...
Электроника   Чехлы                       16340
              Чехлы-аккумуляторы            550
              Штативы и моноподы           3692
              Экшн-камеры                 17133
              Электронные книги           15879

[934 rows x 1 columns]

**Aggfunc** может принимать список функций.

Давайте попробуем узнать среднее значение и количество:

In [ ]:
# Создание сводной таблицы с использованием списка функций: 'mean' и 'count'
pivot_with_mean_and_count = pd.pivot_table(
    df,
    index=['category_name', 'subcategory_name'],
    values=["visits"],
    aggfunc=['mean', 'count']
)

# Вывод результата
pivot_with_mean_and_count

                                            mean  count
                                          visits visits
category_name subcategory_name
Авто          Автоакустика               10674.0      2
              Автомагнитолы              13236.5      2
              Автомобильные инверторы      147.5      2
              Автомобильные компрессоры    598.5      2
              Автомобильные телевизоры    1610.5      2
...                                          ...    ...
Электроника   Чехлы                       8170.0      2
              Чехлы-аккумуляторы           275.0      2
              Штативы и моноподы          1846.0      2
              Экшн-камеры                 8566.5      2
              Электронные книги           7939.5      2

[934 rows x 2 columns]

Если мы хотим увидеть визиты с разбивкой по источникам трафика (**source**), переменная **columns** позволяет нам определить один или несколько столбцов.

Одна из сложностей **pivot_table** - это использование столбцов (**columns**) и значений (**values**).

Помните, что столбцы необязательны - они предоставляют дополнительный способ сегментировать актуальные значения, которые вам нужны.

Функции агрегирования применяются к перечисленным значениям (**values**):

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], columns=["source"], aggfunc='sum'])**

In [ ]:
# Создание сводной таблицы с использованием столбцов (columns) для сегментации по источникам трафика (source)
pivot_with_columns = pd.pivot_table(
    df,
    index=['category_name', 'subcategory_name'],
    values=["visits"],
    columns=["source"],
    aggfunc='sum'
)

# Вывод результата
pivot_with_columns

                                        visits
source                                  direct organic
category_name subcategory_name
Авто          Автоакустика                5915   15433
              Автомагнитолы               7783   18690
              Автомобильные инверторы      145     150
              Автомобильные компрессоры    407     790
              Автомобильные телевизоры     975    2246
...                                        ...     ...
Электроника   Чехлы                       4582   11758
              Чехлы-аккумуляторы           219     331
              Штативы и моноподы          1152    2540
              Экшн-камеры                 4757   12376
              Электронные книги           4515   11364

[934 rows x 2 columns]

Теперь вы видите название категории и её подкатегории со значениями объёма трафика по каждой.

Как видно, основная категория включает в себя подкатегорию и это представлено в структуре датафрейма: категория отображена иерархически главной над подкатегорией. Такие датафреймы содержат в себе мультииндекс. Часто при работе с такими датафреймами мультииндекс убирают, чтобы категория была отображена на каждой строчке датафрейма:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"],
               columns=["source"], aggfunc='sum').reset_index()**

In [ ]:
# Сброс мультииндекса для упрощения структуры таблицы
pivot_reset_index = pd.pivot_table(
    df,
    index=['category_name', 'subcategory_name'],
    values=["visits"],
    columns=["source"],
    aggfunc='sum'
).reset_index()

# Вывод результата
pivot_reset_index

       category_name           subcategory_name visits
source                                          direct organic
0               Авто               Автоакустика   5915   15433
1               Авто              Автомагнитолы   7783   18690
2               Авто    Автомобильные инверторы    145     150
3               Авто  Автомобильные компрессоры    407     790
4               Авто   Автомобильные телевизоры    975    2246
..               ...                        ...    ...     ...
929      Электроника                      Чехлы   4582   11758
930      Электроника         Чехлы-аккумуляторы    219     331
931      Электроника         Штативы и моноподы   1152    2540
932      Электроника                Экшн-камеры   4757   12376
933      Электроника          Электронные книги   4515   11364

[934 rows x 4 columns]

В таблице выше суммы визитов **visits** по каждому из источников **source (direct и organic)** представлены в отдельных столбцах. Такой вид таблицы называется «широкий». Он удобен, когда нужно сравнить значения столбцов. Хорошо заметно, например, что в подкатегории «Автомобильные инверторы» количество визитов из источников **direct** и **organic** практически одинаково, а в подкатегории «Автомагнитолы» из источника **organic** пришло почти в два раза больше посетителей, чем из **direct**.

## Расширенная фильтрация сводной таблицы

После того, как вы сгенерировали свои данные, они находятся в **DataFrame**, поэтому можно фильтровать их, используя обычные методы **DataFrame**.

Если вы хотите посмотреть только на одну категорию, например, "Товары для дома":

**data_pivot = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values='visits', columns='source',
                            aggfunc='sum').reset_index()**
**print((data_pivot[data_pivot['category_name']=='Товары для дома']).head(10))**

In [ ]:
# Фильтрация данных для категории "Товары для дома"
data_pivot = pd.pivot_table(
    df,
    index=['category_name', 'subcategory_name'],
    values='visits',
    columns='source',
    aggfunc='sum'
).reset_index()

# Фильтрация по категории "Товары для дома"
filtered_data = data_pivot[data_pivot['category_name'] == 'Товары для дома']

# Вывод первых 10 строк отфильтрованных данных
filtered_data.head(10)

source    category_name          subcategory_name  direct  organic
646     Товары для дома                Аксессуары     219      329
647     Товары для дома    Аксессуары для готовки     216      326
648     Товары для дома        Банки для хранения     113       58
649     Товары для дома         Блюда и салатники     300      550
650     Товары для дома          Бокалы и стаканы     750     1595
651     Товары для дома                       Бра     265      452
652     Товары для дома                      Вазы     142      142
653     Товары для дома         Вешалки напольные     304      562
654     Товары для дома  Встраиваемые светильники     306      563
655     Товары для дома       Выпечка и запекание     698     1460

Или, например, мы можем узнать на какие товары запросы с органического трафика в разы больше, чем с прямого. Для этого создадим в таблице **data_pivot** новый столбец **'ratio'** и сохраните в нём значение отношения органического трафика **'organic'** к прямому **'direct'**.

Отсортируем таблицу по столбцу 'ratio' в порядке убывания. Выведите первые 10 строк.

**data_pivot['ratio'] = data_pivot['organic'] / data_pivot['direct']**

**data_my = data_pivot.sort_values(by = 'ratio', ascending=False)**

**print(data_my.head(10))**

In [ ]:
# Создание нового столбца 'ratio' с отношением органического трафика к прямому
data_pivot['ratio'] = data_pivot['organic'] / data_pivot['direct']

# Сортировка таблицы по столбцу 'ratio' в порядке убывания
data_my = data_pivot.sort_values(by='ratio', ascending=False)

# Вывод первых 10 строк отсортированной таблицы
data_my.head(10)

source,category_name,subcategory_name,direct,organic,ratio
45,Авто,Шины,39638,153859,3.881604
105,Бытовая техника,Стиральные машины,22064,64570,2.926487
468,Спорт и отдых,Велосипеды,16009,46087,2.878818
205,Детские товары,Коляски,18079,52005,2.876542
609,Строительство и ремонт,Сварочные аппараты,6175,17325,2.805668
678,Товары для дома,Компьютерные кресла,6208,17407,2.803963
330,Компьютерная техника,Клавиатуры,6224,17417,2.798361
921,Электроника,Универсальные внешние аккумуляторы,6146,17115,2.784738
866,Электроника,TV-тюнеры,6275,17427,2.777211
117,Бытовая техника,Холодильники,20920,57985,2.771750

# Задачи для самостоятельного выполнения

Для начала давайте представим, что мы являемся аналитиками в фирме по продаже компьютеров, программного обеспечения к ним, а также оказываем услуги по техническому сопровождению. Нам поставлена задача проанализировать участие компании в различных аукционах.

1. Прочитайте и сохраните файл "baza.xlsx" с данными аукционов в переменную data_pd.

In [ ]:
# Чтение данных из файла "baza.xlsx" и сохранение в переменную data_pd
data_pd = pd.read_excel('baza.xlsx')

# Вывод первых строк для проверки
data_pd_head = data_pd.head()

data_pd_head

,Аукцион,Контрагент,Контакт,Менеджер,Продукт,Количество,Цена,Статус
0,424845,Ильин и Ко,Сергей Ильин,Илья Сергеев,Компьютер,4,45200,на рассмотрении
1,312058,Ильин и Ко,Сергей Ильин,Илья Сергеев,Софт,2,37600,на рассмотрении
2,918390,Ильин и Ко,Сергей Ильин,Илья Сергеев,Тех. сопровождение,2,21200,в ожидании
3,997345,Ильин и Ко,Сергей Ильин,Илья Сергеев,Компьютер,5,39100,отменен
4,496901,Шахты плюс,Данил Сидоров,Илья Сергеев,Компьютер,3,13600,выигран

2. Cоздайте сводную таблицу сводную таблицу по столбцу Контрагент:

In [ ]:
# Создание сводной таблицы по столбцу "Контрагент"
pivot_by_contractor = pd.pivot_table(
    data_pd,
    index="Контрагент",
    aggfunc='sum'
)

# Вывод результата
pivot_by_contractor

,Аукцион,Количество,Контакт,Менеджер,Продукт,Статус,Цена
Контрагент,,,,,,,
Альма,1002536,6,Женя СидинЖеня Сидин,Илья СергеевИлья Сергеев,Тех. сопровождениеКомпьютер,в ожиданииотменен,49000
Ильин и Ко,2652638,13,Сергей ИльинСергей ИльинСергей ИльинСергей Ильин,Илья СергеевИлья СергеевИлья СергеевИлья Сергеев,КомпьютерСофтТех. сопровождениеКомпьютер,на рассмотрениина рассмотрениив ожиданииотменен,143100
Кружка и ложка,1198255,11,Виктор ЮдинВиктор ЮдинВиктор ЮдинВиктор Юдин,Павел ПоповПавел ПоповПавел ПоповПавел Попов,Тех. сопровождениеКомпьютерКомпьютерМонитор,выигранвыигранотмененна рассмотрении,108000
Микрошкин,922767,14,Сергей МининСергей МининСергей МининСергей Минин,Павел ПоповПавел ПоповПавел ПоповПавел Попов,КомпьютерКомпьютерТех. сопровождениеСофт,выигранна рассмотрениив ожиданиина рассмотрении,93100
Шахты плюс,2265094,5,Данил СидоровДанил СидоровДанил Сидоров,Илья СергеевИлья СергеевИлья Сергеев,КомпьютерКомпьютерСофт,выигранв ожиданиина рассмотрении,44700

3. Создайте сводную таблицу по нескольким индексируемым столбцам  'Контакт', 'Менеджер':

In [ ]:
# Создание сводной таблицы с несколькими индексируемыми столбцами: 'Контакт', 'Менеджер'
pivot_by_contact_manager = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    aggfunc='sum'
)

# Вывод результата
pivot_by_contact_manager

,,Аукцион,Количество,Контрагент,Продукт,Статус,Цена
Контакт,Менеджер,,,,,,
Виктор Юдин,Павел Попов,1198255,11,Кружка и ложкаКружка и ложкаКружка и ложкаКруж...,Тех. сопровождениеКомпьютерКомпьютерМонитор,выигранвыигранотмененна рассмотрении,108000
Данил Сидоров,Илья Сергеев,2265094,5,Шахты плюсШахты плюсШахты плюс,КомпьютерКомпьютерСофт,выигранв ожиданиина рассмотрении,44700
Женя Сидин,Илья Сергеев,1002536,6,АльмаАльма,Тех. сопровождениеКомпьютер,в ожиданииотменен,49000
Сергей Ильин,Илья Сергеев,2652638,13,Ильин и КоИльин и КоИльин и КоИльин и Ко,КомпьютерСофтТех. сопровождениеКомпьютер,на рассмотрениина рассмотрениив ожиданииотменен,143100
Сергей Минин,Павел Попов,922767,14,МикрошкинМикрошкинМикрошкинМикрошкин,КомпьютерКомпьютерТех. сопровождениеСофт,выигранна рассмотрениив ожиданиина рассмотрении,93100

4. По умолчанию сводная таблица выводится по всем числовым полям, однако это не всегда удобно, а иногда и лишено смысла, поэтому можно выводить сводные данные только по отдельным столбцам. Выведите только столбец "Стоимость", для этого добавьте параметр values=['Цена']:

In [ ]:
# Создание сводной таблицы, выводящей данные только по столбцу "Цена"
pivot_price_only = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    values=['Цена']

)

# Вывод результата
pivot_price_only

                               Цена
Контакт       Менеджер
Виктор Юдин   Павел Попов   27000.0
Данил Сидоров Илья Сергеев  14900.0
Женя Сидин    Илья Сергеев  24500.0
Сергей Ильин  Илья Сергеев  35775.0
Сергей Минин  Павел Попов   23275.0

5. Столбец с ценой по умолчанию выводит среднее значение, однако нам скорее интересна сумма продаж. Добавляем параметр aggfunc='sum':

In [ ]:
# Создание сводной таблицы с использованием функции суммирования (aggfunc='sum') для столбца "Цена"
pivot_price_sum = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    values=['Цена'],
    aggfunc='sum'
)

# Вывод результата
pivot_price_sum

                              Цена
Контакт       Менеджер
Виктор Юдин   Павел Попов   108000
Данил Сидоров Илья Сергеев   44700
Женя Сидин    Илья Сергеев   49000
Сергей Ильин  Илья Сергеев  143100
Сергей Минин  Павел Попов    93100

6. С помощью параметра columns выведите в столбцы наименование продуктов:

In [ ]:
# Создание сводной таблицы с отображением продуктов в столбцах
pivot_with_products = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    values=['Цена'],
    columns=['Продукт'],
    aggfunc='sum'
)

# Вывод результата
pivot_with_products

                                Цена
Продукт                    Компьютер Монитор     Софт Тех. сопровождение
Контакт       Менеджер
Виктор Юдин   Павел Попов    83900.0  9300.0      NaN            14800.0
Данил Сидоров Илья Сергеев   38000.0     NaN   6700.0                NaN
Женя Сидин    Илья Сергеев   42000.0     NaN      NaN             7000.0
Сергей Ильин  Илья Сергеев   84300.0     NaN  37600.0            21200.0
Сергей Минин  Павел Попов    43900.0     NaN  46900.0             2300.0

7. Наверное вы обратили внимание, что в ячейках, где нет данных пусто, хотя нам привычнее, что бы в таких полях указывалось бы значение 0. Добавьте параметр fill_value=0:

In [ ]:
# Создание сводной таблицы с заполнением пустых ячеек значением 0
pivot_with_products_filled = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    values=['Цена'],
    columns=['Продукт'],
    aggfunc='sum',
    fill_value=0
)

# Вывод результата
pivot_with_products_filled

                                Цена
Продукт                    Компьютер Монитор   Софт Тех. сопровождение
Контакт       Менеджер
Виктор Юдин   Павел Попов      83900    9300      0              14800
Данил Сидоров Илья Сергеев     38000       0   6700                  0
Женя Сидин    Илья Сергеев     42000       0      0               7000
Сергей Ильин  Илья Сергеев     84300       0  37600              21200
Сергей Минин  Павел Попов      43900       0  46900               2300

8. Вероятно полезно было бы рассматривать эффективность деятельности наших менеджеров не только по стоимости продаж, но и по их количеству. Добавьте в параметр values переменную  "Количество"

In [ ]:
# Создание сводной таблицы с добавлением столбца "Количество" в values
pivot_with_products_and_quantity = pd.pivot_table(
    data_pd,
    index=['Контакт', 'Менеджер'],
    values=['Цена', 'Количество'],
    columns=['Продукт'],
    aggfunc='sum',
    fill_value=0
)

# Вывод результата
pivot_with_products_and_quantity

                           Количество                                  \
Продукт                     Компьютер Монитор Софт Тех. сопровождение
Контакт       Менеджер
Виктор Юдин   Павел Попов           6       4    0                  1
Данил Сидоров Илья Сергеев          4       0    1                  0
Женя Сидин    Илья Сергеев          4       0    0                  2
Сергей Ильин  Илья Сергеев          9       0    2                  2
Сергей Минин  Павел Попов           8       0    4                  2

                                Цена
Продукт                    Компьютер Монитор   Софт Тех. сопровождение
Контакт       Менеджер
Виктор Юдин   Павел Попов      83900    9300      0              14800
Данил Сидоров Илья Сергеев     38000       0   6700                  0
Женя Сидин    Илья Сергеев     42000       0      0               7000
Сергей Ильин  Илья Сергеев     84300       0  37600              21200
Сергей Минин  Павел Попов      43900       0  46900               2300

9. Выведите продажи только менеджера "Илья Сергеев":

In [ ]:
# Фильтрация данных для менеджера "Илья Сергеев"
sales_ilya_serdeev = pivot_with_products_and_quantity.loc[pd.IndexSlice[:, "Илья Сергеев"], :]

# Вывод результата
sales_ilya_serdeev

                           Количество                                  \
Продукт                     Компьютер Монитор Софт Тех. сопровождение
Контакт       Менеджер
Данил Сидоров Илья Сергеев          4       0    1                  0
Женя Сидин    Илья Сергеев          4       0    0                  2
Сергей Ильин  Илья Сергеев          9       0    2                  2

                                Цена
Продукт                    Компьютер Монитор   Софт Тех. сопровождение
Контакт       Менеджер
Данил Сидоров Илья Сергеев     38000       0   6700                  0
Женя Сидин    Илья Сергеев     42000       0      0               7000
Сергей Ильин  Илья Сергеев     84300       0  37600              21200